language: python
python:
    - "2.6"
    - "2.7"
    - "3.3"
    - "3.4"
services:
    - mongodb
    - rabbitmq
#addons:
    #postgresql: "9.4"
install:
    - pip install --allow-all-external -r requirements.txt
    - pip install coveralls httpbin pyproxy>=0.1.6
    - pip install -e .
script:
    - coverage run setup.py test
after_success:
    - coverage combine
    - coveralls
